wandb_version: 1

aug_ration:
  value: 0.3
dropout:
  value: 0.3
hidden_dim:
  value: 512
num_heads:
  value: 8
num_samples:
  value: 300
pre_lr:
  value: 0.003211557565777273
weight_decay:
  value: 8.147798388820622e-05
