wandb_version: 1

aug_ration:
  value: 0.2
dropout:
  value: 0.3
hidden_dim:
  value: 512
num_heads:
  value: 4
num_samples:
  value: 100
pre_lr:
  value: 0.004817138117762553
weight_decay:
  value: 2.9105998803111145e-05
