wandb_version: 1

aug_ration:
  value: 0.2
dropout:
  value: 0.3
hidden_dim:
  value: 256
num_heads:
  value: 4
num_samples:
  value: 100
pre_lr:
  value: 0.00011195170202742943
weight_decay:
  value: 0.0004570095627567251
