wandb_version: 1

aug_ration:
  value: 0.3
dropout:
  value: 0.5
hidden_dim:
  value: 512
num_heads:
  value: 4
num_samples:
  value: 100
pre_lr:
  value: 0.002019903879190312
weight_decay:
  value: 1.648192090619923e-05
