wandb_version: 1

aug_ration:
  value: 0.2
dropout:
  value: 0.5
hidden_dim:
  value: 512
num_heads:
  value: 8
num_samples:
  value: 300
pre_lr:
  value: 7.61307626330002e-05
weight_decay:
  value: 1.2595272298617193e-05
