wandb_version: 1

aug_ration:
  value: 0.2
dropout:
  value: 0.5
hidden_dim:
  value: 512
num_heads:
  value: 4
num_samples:
  value: 100
pre_lr:
  value: 0.004352420902788227
weight_decay:
  value: 9.79948721045234e-05
